// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "users",
    columns: [
      { name: "name", type: "string" },
      { name: "email", type: "email", unique: true },
    ],
  },
  {
    name: "projects",
    columns: [
      { name: "name", type: "string" },
      { name: "owner", type: "link", link: { table: "users" } },
      { name: "goalDescription", type: "string" },
      { name: "adminIds", type: "multiple" },
      { name: "champion", type: "link", link: { table: "users" } },
      { name: "habitScheduleTemplate", type: "text" },
      {
        name: "startDate",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
    ],
  },
  {
    name: "weeklyHabitSchedules",
    columns: [
      { name: "weekStartDate", type: "datetime" },
      { name: "days", type: "text" },
      { name: "project", type: "link", link: { table: "projects" } },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type Projects = InferredTypes["projects"];
export type ProjectsRecord = Projects & XataRecord;

export type WeeklyHabitSchedules = InferredTypes["weeklyHabitSchedules"];
export type WeeklyHabitSchedulesRecord = WeeklyHabitSchedules & XataRecord;

export type DatabaseSchema = {
  users: UsersRecord;
  projects: ProjectsRecord;
  weeklyHabitSchedules: WeeklyHabitSchedulesRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Phil-Leggetter-s-workspace-hc84d7.eu-west-1.xata.sh/db/habit-dabit",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
